let input = $("<input id='display'>");
$(".td").append(input);
let input1 = $("<input type='button' value='c'>");
$("input1").click(()=>{display.value += ''});
$(".td1").append(input1);
let input2=$("<input type='button' value='1'>");
$("input1").click(()=>{display.value += '1'});
input2.css({
    
})
$(".td2").append(input2);
let input3=$("<input type='button' value='2'>");
$("input1").click(()=>{display.value += '2'});
$(".td2").append(input3);
let input4=$("<input type='button' value='3'>");
$("input1").click(()=>{display.value += '3'});
$(".td2").append(input4);
let input5=$("<input type='button' value='+'>");
$("input1").click(()=>{display.value += '+'});
$(".td2").append(input5);
let input6=$("<input type='button' value='4'>");
$("input1").click(()=>{display.value += '4'});
$(".td3").append(input6);
let input7=$("<input type='button' value='5'>");
$("input1").click(()=>{display.value += '5'});
$(".td3").append(input7);
let input8=$("<input type='button' value='6'>");
$("input1").click(()=>{display.value += '6'});
$(".td3").append(input8);
let input9=$("<input type='button' value='-'>");
$("input1").click(()=>{display.value += '-'});
$(".td3").append(input9);
let input10=$("<input type='button' value='7'>");
$("input1").click(()=>{display.value += '7'});
$(".td4").append(input10);
let input11=$("<input type='button' value='8'>");
$("input1").click(()=>{display.value += '8'});
$(".td4").append(input11);
let input12=$("<input type='button' value='9'>");
$("input1").click(()=>{display.value += '9'});
$(".td4").append(input12);
let input13=$("<input type='button' value='*'>");
$("input1").click(()=>{display.value += '*'});
$(".td4").append(input13);
let input_1=$("<input type='button' value='%'>");
$("input1").click(()=>{display.value += '%'});
$(".td5").append(input_1);
let input_2=$("<input type='button' value='/'>");
$("input1").click(()=>{display.value += '/'});
$(".td5").append(input_2);
let input_3=$("<input type='button' value='.'>");
$("input1").click(()=>{display.value += '.'});
$(".td5").append(input_3);
let input_4=$("<input type='button' value='='>");
$(input_4).click(()=>eval(display.value));
$(".td5").append(input_4);